//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reciclemos_v3.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class materiales_detalle
    {
        public int idMatDet { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idMateriales { get; set; }
    
        public virtual materiales materiales { get; set; }
    }
}
