//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reciclemos_v3.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud_detalle
    {
        public int idSolDet { get; set; }
        public Nullable<int> idSolicitud { get; set; }
        public Nullable<int> idMat { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string horario { get; set; }
        public string descripcion { get; set; }
    
        public virtual materiales materiales { get; set; }
        public virtual solicitud solicitud { get; set; }
    }
}
